### ISSUE TITLE
 Error: object 'color_scheme' not found 

### ISSUE THREAD

**Issue by eyleencorrales** [PoisonAlien/trackplot#1]
Hi!
I got the following error: 
` Error in .extract_cytoband(chr = chr, refBuild = build) : 
  object 'color_scheme' not found ` 
I think 'color_scheme' (line: 486) might need to be replaced for 'colorSheme'

**Comment by PoisonAlien** [comment]
Hi,
Thanks for testing and you're correct. There was a type.. I have fixed it. 
Let me know if it works.

**Comment by eyleencorrales** [comment]
Hi,
It works fine now 🙂 Many thanks!
Best,

Eyleen
