### ISSUE TITLE
Trackplot cannot detect local installation of bwtools

### ISSUE THREAD

**Issue by AlBaarS** [PoisonAlien/trackplot#10]
Hello,

This may be less of an issue but rather a question (or perhaps a suggestion). I am trying to run trackplot on a remote linux server. While we as students mostly have free reign, there are some limitations, one of which is that we cannot install software globally with sudo. So I have installed bwtools, and confirmed that it works, but trackplot cannot find its location, as it searches for a global installation. My question to you is; how could I make trackplot use my local installation of bwtools?

**Comment by PoisonAlien** [comment]
Hi,
You could try this solution. I have `bwtool` binary located in Documents `/Users/anand/Documents/bwtool_bin/`
Adding this to `PATH` within R works fine. 

```r
#Add the directory containing bwtool binary to the PATH
Sys.setenv(PATH = paste("/Users/anand/Documents/bwtool_bin", Sys.getenv("PATH"), sep=":"))

#Make sure trackplot detects bwtool
trackplot:::.check_bwtool()
Checking for bwtool installation
    All good! Found bwtool at: /Users/anand/Documents/bwtool_bin/bwtool
```

Hope this helps.

PS: I am on macOS but should be the same for nix.

**Comment by AlBaarS** [comment]
Hi,

Thank you for the quick response. I've added the code (and of course changed my directory), but it does not seem to work:
`# importing the trackplot source file
download.file(url = "https://raw.githubusercontent.com/PoisonAlien/trackplot/master/R/trackplot.R", destfile = "trackplot.R")
source('trackplot.R')

Sys.setenv(PATH = paste("/home/alejandro/software/bwtools-1.0/bwtool", Sys.getenv("PATH"), sep=":"))`

Yields:

`trying URL 'https://raw.githubusercontent.com/PoisonAlien/trackplot/master/R/trackplot.R'
Content type 'text/plain; charset=utf-8' length 57556 bytes (56 KB)
==================================================
downloaded 56 KB

Error in .check_bwtool() :
  Could not locate bwtool. Download it from here: https://github.com/CRG-Barcelona/bwtool/releases
Calls: track_extract -> .check_bwtool
Execution halted`

And when I add the `trackplot:::.check_bwtool()` checking step:
`trying URL 'https://raw.githubusercontent.com/PoisonAlien/trackplot/master/R/trackplot.R'
Content type 'text/plain; charset=utf-8' length 57556 bytes (56 KB)
==================================================
downloaded 56 KB

Error in loadNamespace(x) : there is no package called ‘trackplot’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted`

Trying to load the rtrackplot file as a package (as described in the installation instructions) sadly doesn't seem to work either. Any idea what could be happening here and how to fix it?

**Comment by PoisonAlien** [comment]
Hi,

Your setenv should be a directory and not the binary itself.


```
#Change this to
Sys.setenv(PATH = paste("/home/alejandro/software/bwtools-1.0/bwtool", Sys.getenv("PATH"), sep=":"))
#this
Sys.setenv(PATH = paste("/home/alejandro/software/bwtools-1.0", Sys.getenv("PATH"), sep=":"))
```

**Comment by AlBaarS** [comment]
Hi,

Sorry that I keep bothering you with this. I changed it again, but it still yields the same error messages as stated previously. I have confirmed that the trackplot.R file is downloaded, it's in my home directory from which I also (try to) run my R script. It does seem to be sourced correctly as it uses the native .check_bwtool() correctly, but it refuses to call it from my script. I have also tried to add the setenv command to the trackplot.R script, but to no avail.

**Comment by PoisonAlien** [comment]
Hi, 
It's no bother at all. Happy to help. 
I can't seem to figure out the issue as well. Could you maybe post your entire commands in sequence?

Source the script, set the env and test it detects.

**Comment by AlBaarS** [comment]
Hi, I wanted to let you know I've been an absolute moron and missed a typo: it should be "/home/alejandro/software/bwtool-1.0" instead of "/home/alejandro/software/bwtools-1.0" (without the s). The programme is now working properly :)

So for anyone else in the future; it works fine with a local installation with the instructions described above, just don't be a butt like me and fix your typos :P
