### ISSUE TITLE
Collapsing transcripts..

### ISSUE THREAD

**Issue by houruiyan** [PoisonAlien/trackplot#11]
Hi, thank you for developing these package. It is convenient.

But I meet problems when I plot
`bigWigs <-list.files(path = '/storage/yhhuang/users/ruiyan/15organ/file_to_Sinto/',pattern = '\\.bw$')
track_data = track_extract(bigWigs = bigWigs, loci = "5:68,213,737-68,303,821")

png("p3_sa_para.png", 640, 480)
track_plot(summary_list = track_data, draw_gene_track = TRUE, build = "hg38")`

Finally, I got this error when I plot.
<img width="704" alt="image" src="https://user-images.githubusercontent.com/56068158/163715789-16a20030-4969-4de4-a92e-1e04031ef0ee.png">

**Comment by PoisonAlien** [comment]
Hi,

I don't see any error here. It seems it has worked. Those are just verbose logs. Please check the png generated and let me know.

**Comment by houruiyan** [comment]
Yes, sorry. Because when I plot in Rstudio, it produce this question  _plot.new() : figure margins too large"_
Then I use this commond `png("p3_sa_para.png", 640, 480)`. I found the size of picture is zero. But when I extend the plot in Rstudio manully, I can see the result. Thank you for your quick response!

**Comment by PoisonAlien** [comment]
When you are done plotting, you will have to call `dev.off()` to see the saved plot. 

```r
png("p3_sa_para.png", 640, 480)
track_plot(summary_list = track_data, draw_gene_track = TRUE, build = "hg38")
dev.off()
```

Hope this helps.

**Comment by houruiyan** [comment]
Yes, it is usful! Thank you! But I still have another simple question.  the highlight color , I also want to change to orange . My color is ugly. How can I meet that? Thank you.
![image](https://user-images.githubusercontent.com/56068158/163912615-4f1e89fc-b691-427e-bf1a-29aef888c19c.png)

**Comment by houruiyan** [comment]
Thank you very much! This is helpful. I meet another question. I plot a picture. I want to make there is not gap. How can I do this? Thank you! Hope to get your reply.
![image](https://user-images.githubusercontent.com/56068158/163945492-11af6afd-c23c-4ebb-a3dc-cbcb1c66ddce.png)
