### ISSUE TITLE
Plot multiple tracks overlaid

### ISSUE THREAD

**Issue by dgoekbuget** [PoisonAlien/trackplot#14]
Hi, is or would it be possible to overlay tracks in one graph as, say a "line plot"? Those plots can be helpful to compare, e.g. effects of a treatment on binding of a transcription factor.

**Comment by PoisonAlien** [comment]
Hi,

Thank you for the feature request, and I apologize for the delay.  It has been a while, and this is implemented now in 1.7.0.  You can use the `track_overlay` argument to combine all tracks into a single-line plot.  

See [here](https://github.com/PoisonAlien/trackplot?tab=readme-ov-file#collapse-all-tracks-into-a-single-track)
