### ISSUE TITLE
 Could not locate mysql.

### ISSUE THREAD

**Issue by chenggang108** [PoisonAlien/trackplot#15]
Hi, I am trying to use trackplot, but it show the error below. I have installed mysql either by homebrew or conda. Neither can be detected. Can you please help with it?

```r
> track_plot(summary_list = track_data)
Missing gene model. Trying to query UCSC genome browser..
Error in .check_mysql() : Could not locate mysql.
Install:
 apt install mysql-server [Debian]
 yum install mysql-server [centOS]
 brew install mysql [macOS]
 conda install -c anaconda mysql [conda]
Called from: .check_mysql()
```

Thanks
Gang

**Comment by PoisonAlien** [comment]
Hi,
The error says it all. You need to install mysql().

**Comment by chenggang108** [comment]
Hi, Thank you for your reply. I did install MySQL by conda at local(I use Mac). How does Trackplot locate it? Should I give a path?ThanksSent from my iPhoneOn Sep 21, 2022, at 1:54 AM, Anand Mayakonda ***@***.***> wrote:﻿
Hi,
The error says it all. You need to install mysql().

**Comment by PoisonAlien** [comment]
Hi,
If `mysql` is under the path then it should work without any issues.
Could you find it from the terminal -  if you run `which mysql` or `Whereis mysql`?
