### ISSUE TITLE
mysql cmd needs to be updated

### ISSUE THREAD

**Issue by gabrielascui** [PoisonAlien/trackplot#19]
Hi,

This script is great!

I found a problem when using build = "mm39" as the cytoBand is actually called cytoBandIdeo.

The other thing is that the mysql servers seemed to have changed in UCSC genome browser. 

https://genome.ucsc.edu/goldenPath/help/mysql.html

Best,

Gabriel

**Comment by PoisonAlien** [comment]
Hi,

Sorry for the tardy response. Thanks for pointing out the MySQL and cytoBand issue. 
I have updated the MySQL commands. `track_extract` has an additional argument `ideoTblName` with which you can specify the table name for ideograms. 

Feel free to reopen the issue if needed.
