### ISSUE TITLE
Maximum track limit

### ISSUE THREAD

**Issue by peterpdu** [PoisonAlien/trackplot#23]
Hello,

I am having an issue with showing more than 15 tracks at a time using the `track_plot` function. It throws the following error: `Error in plot.new() : figure margins too large`. Is there a way to bypass this limit?

**Comment by PoisonAlien** [comment]
Hi,

You need to save it to a pdf (or png tiff) with enough height and width so that the plotting device can accomodate all the layers.

**Comment by peterpdu** [comment]
Great, thank you!
