### ISSUE TITLE
can't install dependencies on MacOS 12.6.8

### ISSUE THREAD

**Issue by Sinevadada** [PoisonAlien/trackplot#24]
Hi!
Thank you for the tool. I can't install bwtool and have issues with libbeato. I tried a basic installation and I read all the issues in both github pages, but no solutions helped me. It is a pity that a lot of people could find your application very useful, but can't use it due to the dependencies that are not properly supported by their developers.

**Comment by PoisonAlien** [comment]
Hi,
For macOS I would suggest downloading this prebuild binary for `bwtool` from [here])(https://www.dropbox.com/s/kajx9ya6erzyrim/bwtool_macOS.tar.gz?dl=1)

Make it executable with `chmod`. 
macOS gatekeeper might complain that it can't run the binary downloaded from the internet. If it complains, [allow](https://support.apple.com/en-us/HT202491) it in the security settings. Let me know if it works.

**Comment by Sinevadada** [comment]
> Hi, For macOS I would suggest downloading this prebuild binary for `bwtool` from [here](https://www.dropbox.com/s/kajx9ya6erzyrim/bwtool_macOS.tar.gz?dl=1)
> 
> Make it executable with `chmod`. macOS gatekeeper might complain that it can't run the binary downloaded from the internet. If it complains, [allow](https://support.apple.com/en-us/HT202491) it in the security settings. Let me know if it works.

Great! It worked like a charm! Thank you very much!
