### ISSUE TITLE
unused arguments

### ISSUE THREAD

**Issue by Sinevadada** [PoisonAlien/trackplot#25]
Hi!

Everything worked well, but now I get an error even with the files provided as examples:

```r
Error in read_coldata(bws = bigWigs, build = "hg19") : 
  unused arguments (bws = bigWigs, build = "hg19")
```

Code:
bigWigs = c("H1_Ctcf.bw", "H1_H2az.bw")
bigWigs = read_coldata(bws = bigWigs, build = "hg19")

Could you tell me what is wrong?

**Comment by PoisonAlien** [comment]
Hi,
Make sure you are using the latest version.
