### ISSUE TITLE
Error in plot.window(...) : need finite 'ylim' values

### ISSUE THREAD

**Issue by Sinevadada** [PoisonAlien/trackplot#27]
Hi! How can I fix the error? Could it be due to NA values?

`> profile_plot(ps_refseq)`

Error in plot.window(...) : need finite 'ylim' values
In addition: There were 12 warnings (use warnings() to see them)

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue. Any chance you can share the `ps_refseq` data? You can save it as an RDs file and attched it here.

```r
saveRDS(object = ps_refseq, file = "ps_refseq.RDs")
```
