### ISSUE TITLE
Issue with MySQL when accessing UCSC

### ISSUE THREAD

**Issue by jsangalang** [PoisonAlien/trackplot#28]
Hello! Thanks for the wonderful tool!

I am trying to use `track_extract` but it is giving me an error, saying that it can't access the MySQL server. Is this an error with my command? I have installed `bwtools` and `mysql` via Conda, and the script detects the `PATH`.

Here is the traceback
```
> t = track_extract(colData = bigWigs, 
+                   gene = "ESR1",
+                   build = "hg38")
Querying UCSC genome browser for gene model and cytoband..
Extracting gene models from UCSC:
    Gene: ESR1
    build: hg38
    query: mysql --user genome --host genome-mysql.soe.ucsc.edu -NAD hg38 -e 'select chrom, txStart, txEnd, strand, name, name2, exonStarts, exonEnds from refGene WHERE name2 ="ESR1"'
ERROR 2003 (HY000): Can't connect to MySQL server on 'genome-mysql.soe.ucsc.edu' (110)
File '/mnt/beegfs/scratch/USER/tmp_dir//Rtmpq6eAGa/file6304241c1ce1d' has size 0. Returning a NULL data.table.No features found within the requested loci!
no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfError in if (!grepl(pattern = "^chr", x = chr)) { : 
  argument is of length zero
```

Thanks!

**Comment by PoisonAlien** [comment]
Hi,

Thanks for the issue and I am glad you liked the tool. 
[ERROR 2003](https://stackoverflow.com/questions/1673530/error-2003-hy000-cant-connect-to-mysql-server-on-127-0-0-1-111) seems to be a network issue. I guess you are behind a proxy wall that's preventing MySQL from accessing the UCSC database. Unfortunately, I can't help you much with this.
