### ISSUE TITLE
Function Structure Issue: 'track_plot' Error with No 'p' Argument

### ISSUE THREAD

**Issue by BolisLab** [PoisonAlien/trackplot#32]
Good morning, I am trying to run this code using the "track_plot" function and I get this error that I cannot resolve. The structure of the function is as follows, and there is no "p" argument. Is it a problem related to the structure of the function itself? The examples on the browser don't work either and give the same error. How can it be solved?

`> #  TrackPlot Execution:
> trackplot::track_plot(summary_list = t, col = track_cols, show_ideogram = TRUE, peaks = CTCF_peak_files)
Error in layout.matrix(mat = matrix(data = data), heights = lo_heights) : 
  argument "p" is missing, with no default`

**Comment by PoisonAlien** [comment]
Hi,

It could be due to a conflict between multiple `layout()` functions. If you have loaded packages like `plotly`, please unload them and try again.

**Comment by BolisLab** [comment]
Dear Anand, 

I wanted to let you know that the issue has been resolved. It was indeed due to a conflict between multiple layout() functions. Following your advice, we unloaded the conflicting packages, and everything is now working perfectly. 

Thank you very much for your help. 

Best Regards. 


Da: "Anand Mayakonda" ***@***.***> 
A: "PoisonAlien/trackplot" ***@***.***> 
Cc: "BolisLab" ***@***.***>, "Author" ***@***.***> 
Inviato: Venerdì, 15 marzo 2024 18:48:57 
Oggetto: Re: [PoisonAlien/trackplot] Function Structure Issue: 'track_plot' Error with No 'p' Argument (Issue #32) 





Hi, 

It could be due to a conflict between multiple layout() functions. If you have loaded packages like plotly , please unload them and try again. 

— 
Reply to this email directly, [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FPoisonAlien%2Ftrackplot%2Fissues%2F32%23issuecomment-2000154837&e=d1becced&h=2df5e77f&f=y&p=y | view it on GitHub ] , or [ https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBDWEELP7SY5PN2L6B6SDA5TYYMYATAVCNFSM6AAAAABEYKKFIKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMBQGE2TIOBTG4&e=d1becced&h=3ac62b28&f=y&p=y | unsubscribe ] . 
You are receiving this because you authored the thread. Message ID: ***@***.***> 




------

L'Istituto Mario Negri IRCCS con tutti i suoi ricercatori
ringrazia chi ha generosamente sostenuto la sua attivita'.
Continua a sostenerci per mantenere indipendente
la nostra ricerca scientifica.

Clicca qui per scoprire come sostenerci:

https://www.marionegri.it/aiuta-la-ricerca

**Comment by PoisonAlien** [comment]
Hi,
Thank you for the issue. I have pushed a fix; it should now work even with `plotly` loaded.
