### ISSUE TITLE
Custom gene annotation - alternative to UCSC

### ISSUE THREAD

**Issue by jcm6t** [PoisonAlien/trackplot#36]
I am interested in RNA-seq bigwig visualization of gene exon read coverage but the experiment is for non black6 mice. 

Enhancement request: read a custom annotation file (eg GTF) instead of going to UCSC.

Thanks.
Joe.

**Comment by PoisonAlien** [comment]
Hi,

This is already implemented. You can pass a custom gtf to `track_extract()` with the argument `gtf`. Let me know if this works.

**Comment by jcm6t** [comment]
Thanks, I must have missed it in the documentation. I'll close this and reopen if there's an issue.
