### ISSUE TITLE
Issue Encountered with Script Sourcing

### ISSUE THREAD

**Issue by XuanrZhang** [PoisonAlien/trackplot#38]
Hi @PoisonAlien,

Thank you for developing this useful script.

I encountered the following error when sourcing the code and am unsure if it might be a bug. Could you provide any suggestions for resolving this issue?

> source("https://github.com/PoisonAlien/trackplot/blob/master/R/trackplot.R?raw=true")
Error in source("https://github.com/PoisonAlien/trackplot/blob/master/R/trackplot.R?raw=true") : 
  https://github.com/PoisonAlien/trackplot/blob/master/R/trackplot.R?raw=true:1637:29: unexpected '>'
1636:     
1637:     dt = split(dt, dt$ord) |>

Thank you for your assistance.

Best regards,
Xuan

**Comment by PoisonAlien** [comment]
Hi,
What version of R are you working with?

**Comment by XuanrZhang** [comment]
Hi @PoisonAlien,
I used R version 4.0.0. It used to work.

**Comment by PoisonAlien** [comment]
I see. Could you try installing the script as a package and see if it helps?

```r
remotes::install_github(repo = "poisonalien/trackplot")
```

**Comment by XuanrZhang** [comment]
Hi @PoisonAlien,

I think the code requires the latest version of data.table (1.15.4). The error was resolved after I upgraded to this version.
Thank you for your attention.

Best regards,
Xuan
