### ISSUE TITLE
how to save the plot generated by track_plot

### ISSUE THREAD

**Issue by lexie-lee** [PoisonAlien/trackplot#40]
Hello, I am wondering how to save the figures generated by track_plot? ggsave can not save the plots.

Thanks.

**Comment by yvazirabad** [comment]
Hello,
Why was this closed without any resolution? Please re-open so others can benefit from any solution.

**Comment by PoisonAlien** [comment]
Hi,

Just use the commands for your favorite image (png, pdf, etc.) before plotting. See [here](https://www.datamentor.io/r-programming/saving-plot) for examples
